name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm infrastructure deletion"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: true
  TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}

jobs:
  destroy:
    if: github.actor == 'Mubarek-Amin' && github.event.inputs.confirm_destroy == 'DESTROY'
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy
        run: terraform destroy -input=false -auto-approve
